name: Actions CI - Next.js version 14 static site export, GitHub Actions Build and Deploy
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest source
        uses: actions/checkout@v3
      - name: Node environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Pnpm ğŸ§¬
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: true
      - name: Install dependencies âš™ï¸
        run: pnpm install
      - name: Build ğŸ—ï¸
        run: |
          npm run build
          touch out/.nojekyll
      - name: Deploy ğŸš€
        env:
          # NEXT_PUBLIC_WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          NEXT_PUBLIC_WEATHER_API_KEY: 5e49b1e8c77e4a0dbe922417231511
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
          clean: true
